export const VALIDATION_ERRORS = {
  REQUIRED: 'REQUIRED',
  EMAIL_INVALID: 'EMAIL_INVALID',
  MIN_LENGTH: 'MIN_LENGTH',
  MAX_LENGTH: 'MAX_LENGTH',
  REGEX: 'REGEX',
  INVALID_TYPE: 'INVALID_TYPE',
  INVALID_VALUE: 'INVALID_VALUE',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_USERNAME: 'INVALID_USERNAME',
  INVALID_NAME: 'INVALID_NAME',
} as const;
